##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##

FROM registry.access.redhat.com/ubi10/ubi-minimal:latest
RUN microdnf -y install nodejs shadow-utils jq
RUN microdnf -y update
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --only=production
COPY app/index.js ./
COPY app/src/*.js ./src/
COPY app/src/common/*.js ./src/common/
COPY scripts/skxstatus /usr/local/bin
COPY scripts/skxstart /usr/local/bin
COPY scripts/skxhosts /usr/local/bin
RUN useradd --uid 10000 runner
USER 10000
EXPOSE 8085
CMD ["node","index.js"]
